name: Test & Lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx eslint .

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: eslint-error-log
          path: /home/runner/.npm/_logs

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run test

      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-error-log
          path: /home/runner/.npm/_logs
